#Without Build Image Config

kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: quarkus-mandrel-native-template
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: quarkus-mandrel-native
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: "quarkus-mandrel-native"
      template:
        metadata:
          labels:
            app: "quarkus-mandrel-native"
        spec:
          containers:
            - name: quarkus-mandrel-native
              image: image-registry.openshift-image-registry.svc:5000/test/quarkus-mandrel-native
              ports:
                - containerPort: 8080
                  port: "TCP"
              volumeMounts:
                - name: application-config
                  mountPath: "/deployments/config"
                  readOnly: true
        volumes:
          - name: application-config
            configMap:
              name: quarkus-app-config
              items:
                - key: application.properties
                  path: application.properties
      triggers:
        - type: ConfigChange
        - type: ImageChange
        - imageChangeParams:
          automatic: true
          containerNames:
            - "quarkus-mandrel-native"
          from:
            kind: ImageStreamTag
            name: image-registry.openshift-image-registry.svc:5000/test/quarkus-mandrel-native
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%

  - kind: Service
    apiVersion: v1
    metadata:
      name: quarkus-mandrel-native
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: quarkus-mandrel-native

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: quarkus-mandrel-native
    spec:
      to:
        kind: Service
        name: quarkus-mandrel-native
        weight: 100
      port:
        targetPort: 8080-tcp
        wildcardPolicy: None